// Generated by `npm run sync:exercises` — do not edit.
import type { ExerciseSet } from "./types";
import s0 from "./data/articles-definite-indefinite.json" with { type: "json" };
import s1 from "./data/imperative.json" with { type: "json" };
import s2 from "./data/modal-verbs.json" with { type: "json" };
import s3 from "./data/negation-nicht-kein.json" with { type: "json" };
import s4 from "./data/past-sein-haben.json" with { type: "json" };
import s5 from "./data/perfect-tense.json" with { type: "json" };
import s6 from "./data/personal-pronouns.json" with { type: "json" };
import s7 from "./data/plural-nouns.json" with { type: "json" };
import s8 from "./data/present-tense-regular.json" with { type: "json" };
import s9 from "./data/present-tense-stem-change.json" with { type: "json" };
import s10 from "./data/sein-haben.json" with { type: "json" };
import s11 from "./data/separable-verbs.json" with { type: "json" };

export const EXERCISE_SETS: Record<string, ExerciseSet> = {
  "articles-definite-indefinite": s0 as ExerciseSet,
  "imperative": s1 as ExerciseSet,
  "modal-verbs": s2 as ExerciseSet,
  "negation-nicht-kein": s3 as ExerciseSet,
  "past-sein-haben": s4 as ExerciseSet,
  "perfect-tense": s5 as ExerciseSet,
  "personal-pronouns": s6 as ExerciseSet,
  "plural-nouns": s7 as ExerciseSet,
  "present-tense-regular": s8 as ExerciseSet,
  "present-tense-stem-change": s9 as ExerciseSet,
  "sein-haben": s10 as ExerciseSet,
  "separable-verbs": s11 as ExerciseSet,
};
